version: "3.9"

services:
  mcp-docassemble:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-docassemble:latest
    container_name: mcp-docassemble
    environment:
      DOCASSEMBLE_BASE_URL: ${DOCASSEMBLE_BASE_URL:?Set DOCASSEMBLE_BASE_URL}
      DOCASSEMBLE_API_KEY: ${DOCASSEMBLE_API_KEY:?Set DOCASSEMBLE_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["mcp-docassemble", "serve"]

  mcp-docassemble-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mcp-docassemble:dev
    container_name: mcp-docassemble-dev
    environment:
      DOCASSEMBLE_BASE_URL: ${DOCASSEMBLE_BASE_URL:-http://localhost}
      DOCASSEMBLE_API_KEY: ${DOCASSEMBLE_API_KEY:-change-me}
      MCP_DOCASSEMBLE_LIVE_TESTS: ${MCP_DOCASSEMBLE_LIVE_TESTS:-0}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    stdin_open: true
    tty: true
    command: ["mcp-docassemble", "serve"]
    profiles: ["dev"]
